import Head from 'next/head';
import client from '../data/gql-client';
import { getMostPopular } from '../data/queries';
import { useEffect } from 'react';
import Layout from '../components/layout';

export default function Home({mostPopular}) {

  useEffect(() => {
    console.log(mostPopular);
    return () => {
      
    };
  }, []);

  return (
    <div>
      <Head>
        <title>Catwiki</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <section>This is just a section</section>
      </Layout>
    </div>
  )
}

export async function getServerSideProps() {
  const { data } = await client.query({
    query: getMostPopular
  });

  return { 
    props: {
      mostPopular: data.mostSearched  
    }
  }
}

